-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public."Positions"
(
    id integer NOT NULL,
    position_name character varying(30) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public."Users"
(
    id integer NOT NULL,
    email character varying(20) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public."Employers"
(
    id integer NOT NULL,
    employer_name character varying(20) NOT NULL,
    employer_password character varying(20) NOT NULL,
    employer_phone character(12) NOT NULL,
    employee_website character varying(20) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public."Seekers"
(
    id integer NOT NULL,
    seeker_identification_number character(11) NOT NULL,
    seeker_name character varying(20) NOT NULL,
    seeker_surname character varying(20) NOT NULL,
    seeker_password character varying(30) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public."Staff"
(
    id integer NOT NULL,
    staff_name character varying(20) NOT NULL,
    staff_surname character varying(20) NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE public."Employers"
    ADD FOREIGN KEY (id)
    REFERENCES public."Users" (id)
    NOT VALID;


ALTER TABLE public."Seekers"
    ADD FOREIGN KEY (id)
    REFERENCES public."Users" (id)
    NOT VALID;


ALTER TABLE public."Positions"
    ADD FOREIGN KEY (id)
    REFERENCES public."Users" (id)
    NOT VALID;


ALTER TABLE public."Staff"
    ADD FOREIGN KEY (id)
    REFERENCES public."Users" (id)
    NOT VALID;

END;